name: Deploy Infrastructure

on:
  push:
    branches:
      - main

permissions:
  id-token: write
  contents: read

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:

      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          role-to-assume: arn:aws:iam::302432775392:role/GitHubActionsDeploymentRole
          aws-region: us-east-1

      - name: Zip Lambda Functions
        run: |
          cd lambda/retrieve
          zip -r ../../retrieve.zip .
          cd ../uncompress
          zip -r ../../uncompress.zip .
          cd ../transform
          zip -r ../../transform.zip .
          cd ../../

      - name: Upload Lambda Zip to S3
        run: |
          aws s3 cp retrieve.zip s3://lambda-data-pipeline-code-s3-bucket/lambda/retrieve-${{ github.sha }}.zip
          aws s3 cp uncompress.zip s3://lambda-data-pipeline-code-s3-bucket/lambda/uncompress-${{ github.sha }}.zip
          aws s3 cp transform.zip s3://lambda-data-pipeline-code-s3-bucket/lambda/transform-${{ github.sha }}.zip
          
      - name: Deploy CloudFormation
        run: |
          aws cloudformation deploy \
            --template-file cloudformation/template.json \
            --stack-name data-pipeline-stack \
            --capabilities CAPABILITY_NAMED_IAM \
            --region us-east-1 \
            --parameter-overrides \
              RetrieveLambdaKey=lambda/retrieve-${{ github.sha }}.zip \
              UncompressLambdaKey=lambda/uncompress-${{ github.sha }}.zip \
              TransformLambdaKey=lambda/transform-${{ github.sha }}.zip
     