name: Deploy Infrastructure

on:
  push:
    branches:
      - main
  workflow_dispatch:

permissions:
  id-token: write
  contents: read

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:

      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          role-to-assume: arn:aws:iam::302432775392:role/GitHubActionsDeploymentRole
          aws-region: us-east-1
      
      - name: Get AWS Account ID
        run: |
          ACCOUNT_ID=$(aws sts get-caller-identity --query Account --output text)
          echo "ACCOUNT_ID=$ACCOUNT_ID" >> $GITHUB_ENV

      - name: Deploy first CloudFormation
        run: |
          aws cloudformation deploy \
            --template-file cloudformation/template.json \
            --stack-name aws-serverless-data-pipeline-s3 \
            --capabilities CAPABILITY_NAMED_IAM \
            --region us-east-1 \
            --no-fail-on-empty-changeset

      - name: Zip Lambda Functions
        run: |
          pip install -r requirements.txt -t deps
          
          cd lambda/retrieve || exit 1
          cp -r ../../deps/* .
          zip -r ../../retrieve.zip .
          cd ../../

          cd lambda/uncompress || exit 1
          zip -r ../../uncompress.zip .
          cd ../../
          
          cd lambda/transform || exit 1
          cp -r ../../deps/* .
          zip -r ../../transform.zip .
          cd ../../

      - name: Upload Lambda Zip to S3
        run: |
          aws s3 cp retrieve.zip s3://$ACCOUNT_ID-aws-serverless-data-pipeline-s3-bucket/lambda/retrieve.zip
          aws s3 cp uncompress.zip s3://$ACCOUNT_ID-aws-serverless-data-pipeline-s3-bucket/lambda/uncompress.zip
          aws s3 cp transform.zip s3://$ACCOUNT_ID-aws-serverless-data-pipeline-s3-bucket/lambda/transform.zip

      - name: Deploy second CloudFormation
        run: |
          aws cloudformation deploy \
            --template-file cloudformation/template_2.json \
            --stack-name aws-serverless-data-pipeline-lambda \
            --capabilities CAPABILITY_NAMED_IAM \
            --region us-east-1 \
            --no-fail-on-empty-changeset

      - name: Update Lambda Code
        run: |
          aws lambda update-function-code \
            --function-name retrieve-data \
            --s3-bucket $ACCOUNT_ID-aws-serverless-data-pipeline-s3-bucket \
            --s3-key lambda/retrieve.zip

          aws lambda update-function-code \
            --function-name uncompress-data \
            --s3-bucket $ACCOUNT_ID-aws-serverless-data-pipeline-s3-bucket \
            --s3-key lambda/uncompress.zip

          aws lambda update-function-code \
            --function-name transform-data \
            --s3-bucket $ACCOUNT_ID-aws-serverless-data-pipeline-s3-bucket \
            --s3-key lambda/transform.zip